### PR TITLE
add loading state flag and message

### PR DESCRIPTION
**Pull request by brenna**
@ryanto @samselikoff @heygrady, let me know what you think of this API. 

It's dumb in the sense that the addon doesn't really know anything about AJAX state. 

**Pro:** This keeps the addon lean and flexible. It doesn't make any assumptions about how the consumer is fetching data and doesn't need to manage outside state. This feels in line with what we settled on for [handling custom regex](https://github.com/tedconf/ember-searchable-select/issues/1) as well. 

**Con:** This puts a lot more responsibility on the addon consumer to manage loading state properly. I can envision a scenario where a loading indicator shows up at the same time as a list of results if not managed properly. Do we need some safeguards in there, eg. don't show the loader if the passed in content array is non-empty? Or is that crossing the line as far as who manages state?

### CODE REVIEW

**Comment by heygrady** [comment]
Yes please. Keeping it really dumb is the best. I want to tell it that I'm loading and have it show a "loading" message. I can give it new results and then set loading to false. Perfect! Does it hide the current results when it's set to loading? It probably should.

Not sure about the SVG spinner. Ended up with a CSS spinner on talk star. Was pretty flexible. Depends on if people will need to customize the loading spinner. CSS makes that easier. SVG is cool though.

Wonder if the default message should be "Loading..." but really you could make a case for any message. I went with "Loading..." on talk star based on instructions from Dub and feedback from Sarah.

**Comment by brenna** [comment]
It doesn't currently hide the results while loading - that was where I'm not sure if we're crossing the line in making the component too knowledgeable about outside state. I'm 50/50 on adding vs not adding that tbh. Though I do like the idea of hiding content if loading (vs. my original suggetion of hiding loader if content), seems much safer.

SVG size and colour can be customized with CSS. I'll add some additional BEM classes on the spinner pieces so it's easier to target for a consumer. 

The message is customizable via `loadingMessage` so I think any sane default is ok.

**Comment by brenna** [comment]
Spoke with @samselikoff and I'm convinced it's bet *not* to auto hide the list when the loader is showing. It's possible a consumer might want to keep the previous list while loading the next set of results. For example, see: "Loading Remote Data" with the Select 2 plugin. https://select2.github.io/examples.html

**Comment by brenna** [comment]
:ship:'ing it

**Pull request merged**
