### PR TITLE
- added support for custom option template

### PR DESCRIPTION
**Pull request by 1int**
User can specify 'optionTemplate' value to render custom option template file.

### CODE REVIEW

**Comment by brenna** [comment]
Hi @1int, thanks for your contribution.

In order to accept a PR, we'll need the following:
* [ ] all existing tests passing
* [ ] test coverage for the new feature
* [ ] documentation for the new feature

Additionally, we'd prefer to go in the direction detailed in #11 for this feature, where only the text portion is custom templated. This takes the burden of duplicating state logic out of creating a custom template, unless you have a compelling use case for replacing the entire template.

**Comment by 1int** [comment]
Thanks for the reply!
Where do I add the docs?

**Comment by brenna** [comment]
The docs site is in `tests/dummy/app` https://github.com/tedconf/ember-searchable-select/tree/master/tests/dummy/app. If you run `ember serve` on this project it'll spin up the dummy app.

**Comment by brenna** [comment]
Closing due to inactivity. Please feel free to re-open if more work gets done on this.

**Pull request closed without merging**
