### PR TITLE
Minor change to allow for extendability

### PR DESCRIPTION
**Pull request by jakemoves**
This is an awesome component, thank you!

I wanted to be able to extend it within my Ember app, so I made a minor change. It doesn't affect rendering or functionality, just the way the component exports itself, so I don't believe a test is warranted (or even possible). But let me know if I'm wrong?

### CODE REVIEW

**Comment by brenna** [comment]
Can you tell me more about your use case for making the search box optional? That's the core feature of this addon. Why not use a vanilla select if search isn't required?

**Comment by jakemoves** [comment]
Hey @brenna, I actually didn't intend to include b6b5a6b in the PR, just the extensibility feature (which I thought others might find useful). I figured you wouldn't be interested in a feature that contradicts the core purpose of the component, and what do you know, you're not :) 

I've removed the errant commit, so this PR only covers the minor refactor to allow for in-project extending of the component.

**Comment by samselikoff** [comment]
@jakemoves you should be able to extend the default component like this:

```js
import SearchableSelect from 'ember-searchable-select/components/searchable-select';

export default SearchableSelect.extend({

  foo: Ember.on('didInsertElement', function() {
    alert('hax0red');
  })

});
```

**Comment by brenna** [comment]
@jakemoves Going to assume this one solved without the PR being necessary, but please let us know if this doesn't work for you.

**Pull request closed without merging**
